name: Deploy API to Azure

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allow manual triggers

env:
  AZURE_WEBAPP_NAME: kvantobot-api
  NODE_VERSION: '20.x'

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Create deployment package
      run: |
        # Create a clean deployment package
        zip -r deploy.zip . -x "*.git*" "node_modules/*" "*.zip" ".env" "*.md"
        
    - name: Deploy to Azure using REST API
      env:
        AZURE_WEBAPP_NAME: ${{ env.AZURE_WEBAPP_NAME }}
      run: |
        # Deploy using Kudu REST API
        curl -X POST \
          -H "Content-Type: application/zip" \
          -u "\$${{ env.AZURE_WEBAPP_NAME }}:${{ secrets.AZURE_KUDU_PASSWORD }}" \
          --data-binary "@deploy.zip" \
          "https://${{ env.AZURE_WEBAPP_NAME }}.scm.azurewebsites.net/api/zipdeploy" \
          --fail --show-error --location
